{% set name = "starlette-context" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/starlette_context-{{ version }}.tar.gz
  sha256: f6025753f8ede041778b2f2c3823e2da9df3c2d94832575bcb59374216b7c2b2

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - starlette >=0.27.0

test:
  requires:
    - pip
  imports:
    - starlette_context
  commands:
    - pip check

about:
  home: https://github.com/tomwojcik/starlette-context
  doc_url: https://starlette-context.readthedocs.io
  dev_url: https://github.com/tomwojcik/starlette-context
  summary: Access context in Starlette
  description: |
    starlette-context is a middleware and request-local storage for Starlette framework.
    It allows you to store and access data specific to a request within the context of
    that request. This is particularly useful for storing user information, request IDs,
    or any other data that needs to be accessible throughout the request lifecycle.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
