{% set name = "starlette-context" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/starlette_context-{{ version }}.tar.gz
  sha256: 3242417c9354c067a4ac5009aff762dc0b322074216f664825d5d127108553be

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - starlette >=0.27.0

test:
  imports:
    - starlette_context
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tomwojcik/starlette-context
  doc_url: https://starlette-context.readthedocs.io
  dev_url: https://github.com/tomwojcik/starlette-context
  summary: Access context in Starlette
  description: |
    starlette-context is a middleware and request-local storage for Starlette framework.
    It allows you to store and access data specific to a request within the context of
    that request. This is particularly useful for storing user information, request IDs,
    or any other data that needs to be accessible throughout the request lifecycle.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
